# infra/k8s/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: trading-platform-sa
  namespace: trading-platform

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: trading-platform-role
  namespace: trading-platform
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "persistentvolumeclaims", "configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: trading-platform-rolebinding
  namespace: trading-platform
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: trading-platform-role
subjects:
- kind: ServiceAccount
  name: trading-platform-sa
  namespace: trading-platform